DROP TABLE IF EXISTS BALANCES;

SELECT
  ACCOUNTS.ACCOUNT_ID,
  ACCOUNTS.INITIAL_AMOUNT AS TOTAL INTO BALANCES
FROM
  ACCOUNTS
ORDER BY
  ACCOUNTS.NAME;

INSERT INTO
  BALANCES
SELECT
  TRANSFERS.FROM_ACCOUNT_ID AS ACCOUNT_ID,
  SUM(AMOUNT) * -1 AS TOTAL
FROM
  TRANSFERS
GROUP BY
  TRANSFERS.FROM_ACCOUNT_ID;

INSERT INTO
  BALANCES
SELECT
  TRANSFERS.TO_ACCOUNT_ID AS ACCOUNT_ID,
  SUM(AMOUNT) AS TOTAL
FROM
  TRANSFERS
GROUP BY
  TRANSFERS.TO_ACCOUNT_ID;

INSERT INTO
  BALANCES
SELECT
  OPERATIONS.ACCOUNT_ID,
  SUM(AMOUNT) AS TOTAL
FROM
  OPERATIONS
GROUP BY
  OPERATIONS.ACCOUNT_ID;

SELECT
  BALANCES.ACCOUNT_ID,
  (
    SELECT
      NAME
    FROM
      ACCOUNTS
    WHERE
      ACCOUNTS.ACCOUNT_ID = BALANCES.ACCOUNT_ID
  ) AS NAME,
  SUM(BALANCES.TOTAL) AS TOTAL
FROM
  BALANCES
GROUP BY
  BALANCES.ACCOUNT_ID
ORDER BY
  NAME;