CREATE TABLE IF NOT EXISTS PUBLIC.ACCOUNTS (
    ACCOUNT_ID UUID NOT NULL,
    INITIAL_AMOUNT INTEGER NOT NULL,
    NAME TEXT NOT NULL,
    CONSTRAINT ACCOUNTS_PKEY PRIMARY KEY (ACCOUNT_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.GROUPS (
    GROUP_ID UUID NOT NULL,
    NAME TEXT NOT NULL,
    CONSTRAINT GROUPS_PKEY PRIMARY KEY (GROUP_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.CATEGORIES (
    CATEGORY_ID UUID NOT NULL,
    NAME TEXT NOT NULL,
    GROUP_ID UUID NOT NULL,
    CONSTRAINT CATEGORIES_PKEY PRIMARY KEY (CATEGORY_ID),
    CONSTRAINT GROUP_ID FOREIGN KEY (GROUP_ID) REFERENCES PUBLIC.GROUPS (GROUP_ID) ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID
);

CREATE TABLE IF NOT EXISTS PUBLIC.TRANSFERS (
    AMOUNT INTEGER NOT NULL,
    COMMENTS TEXT,
    CURRENCY TEXT NOT NULL,
    FROM_ACCOUNT_ID UUID NOT NULL,
    "TIMESTAMP" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    TO_ACCOUNT_ID UUID NOT NULL,
    TRANSFER_ID UUID NOT NULL,
    TYPE TEXT NOT NULL,
    CONSTRAINT TRANSFERS_PKEY PRIMARY KEY (TRANSFER_ID),
    CONSTRAINT FROM_ACCOUNT_ID FOREIGN KEY (FROM_ACCOUNT_ID) REFERENCES PUBLIC.ACCOUNTS (ACCOUNT_ID) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT TO_ACCOUNT_ID FOREIGN KEY (TO_ACCOUNT_ID) REFERENCES PUBLIC.ACCOUNTS (ACCOUNT_ID) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS PUBLIC.OPERATIONS (
    ACCOUNT_ID UUID NOT NULL,
    AMOUNT INTEGER NOT NULL,
    AMOUNT_PER_UNIT INTEGER NOT NULL,
    CATEGORY_ID UUID NOT NULL,
    COMMENTS TEXT,
    CURRENCY TEXT,
    GROUP_ID UUID NOT NULL,
    OPERATION_ID UUID NOT NULL,
    "TIMESTAMP" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    TYPE TEXT NOT NULL,
    UNIT_COUNT INTEGER NOT NULL,
    CONSTRAINT OPERATION_ID PRIMARY KEY (OPERATION_ID),
    CONSTRAINT CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.CATEGORIES (CATEGORY_ID) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT GROUP_ID FOREIGN KEY (GROUP_ID) REFERENCES PUBLIC.GROUPS (GROUP_ID) ON UPDATE NO ACTION ON DELETE NO ACTION
);
